#!/bin/sh

# Startup volume
pactl set-sink-volume 0 '20%' &

# Keybord layout setting
setxkbmap -option grp:switch,grp:alt_shift_toggle,grp_led:scroll us,ee &

# DPMS monitor setting (standby -> suspend -> off) (seconds)
xset dpms 300 600 900 &

# Clipboard manager
LC_ALL=C parcellite &

# OSD
dunst &

## GNOME PolicyKit and Keyring
eval $(gnome-keyring-daemon -s --components=pkcs11,secrets,ssh,gpg) &
